# Generated by Django 4.2.7 on 2026-09-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_queueticket_ticket_number_pushsubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at']},
        ),
    ]
