# Generated by Django 4.2.7 on 2026-09-12 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_auditlog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service_category',
            field=models.ForeignKey(blank=True, help_text='If set, this teller only handles this service type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.servicecategory'),
        ),
    ]
