# Generated by Django 4.2.7 on 2026-09-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='service_category',
        ),
        migrations.AddField(
            model_name='user',
            name='service_categories',
            field=models.ManyToManyField(blank=True, help_text='If set, this teller only handles these service types. Leave empty for all services.', related_name='tellers', to='api.servicecategory'),
        ),
    ]
